version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: PostStead_UserService
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pR01#ctj(v*d@!ddA
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    ports:
      - '8081:8081'
    networks:
      pc-network:

  db:
    image: 'postgres:13.1-alpine'
    container_name: PostStead_DB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pR01#ctj(v*d@!ddA
    networks:
      pc-network:

networks:
  pc-network:
