version: '2'

services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    networks:
      - backend-private
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: pjk%ss]@o*e0!@N

networks:
  backend-private:
